# start-docker.ps1 — Build + run the full intelshed stack in Docker (secure by default).
#
# - Ensures a NODE_INGEST_TOKEN exists (runs setup-node-security.ps1 if missing)
# - Auto-detects the PC LAN IP so Caddy issues a TLS cert the Pi can reach
# - Pulls the Cesium Ion token from frontend/.env into the build
# - Writes a repo-root .env consumed by docker-compose, then builds + starts
#
# Usage:
#   .\scripts\start-docker.ps1            # build (if needed) + up -d
#   .\scripts\start-docker.ps1 -Rebuild   # force rebuild

param(
    [switch]$Rebuild
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path $PSScriptRoot -Parent
Set-Location -LiteralPath $Root

function Get-EnvValue([string]$file, [string]$key) {
    if (-not (Test-Path $file)) { return '' }
    $m = Select-String -Path $file -Pattern "^\s*$([regex]::Escape($key))\s*=\s*(.+)$" -ErrorAction SilentlyContinue
    if ($m) { return $m.Matches[0].Groups[1].Value.Trim().Trim('"').Trim("'") }
    return ''
}

Write-Host '=== intelshed Docker stack ===' -ForegroundColor Cyan

# 1) Node token (secure-by-default: backend refuses LAN exposure without it)
$token = Get-EnvValue 'backend\.env' 'NODE_INGEST_TOKEN'
if (-not $token) {
    Write-Host 'No NODE_INGEST_TOKEN found — generating one via setup-node-security.ps1' -ForegroundColor Yellow
    & (Join-Path $PSScriptRoot 'setup-node-security.ps1')
    $token = Get-EnvValue 'backend\.env' 'NODE_INGEST_TOKEN'
}
if ($token) { Write-Host '  Node token: present' -ForegroundColor Green }

# 2) LAN IP for Caddy TLS cert (so the Pi can reach https://<ip>/api/...)
#    Skip virtual adapters (WSL/Hyper-V/Docker) and prefer real LAN ranges.
$candidates = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
        $_.InterfaceAlias -notmatch 'vEthernet|WSL|Hyper-V|Docker|Loopback' -and
        $_.IPAddress -match '^(192\.168\.|10\.|172\.(1[6-9]|2\d|3[01])\.)'
    }
# Prefer 192.168.* > 10.* > 172.* (docker/WSL bridges are usually 172.*)
$lan = ($candidates | Sort-Object @{ Expression = {
    switch -regex ($_.IPAddress) { '^192\.168\.' { 0 } '^10\.' { 1 } default { 2 } }
} } | Select-Object -First 1).IPAddress
if (-not $lan) { $lan = '127.0.0.1' }
# Allow explicit override: $env:WORLDBASE_LAN
if ($env:WORLDBASE_LAN) { $lan = $env:WORLDBASE_LAN }
Write-Host "  PC LAN IP: $lan" -ForegroundColor Green

# 3) Frontend build-time vars (baked into the SPA at build time)
$cesium = Get-EnvValue 'frontend\.env' 'VITE_CESIUM_ION_TOKEN'
if (-not $cesium) {
    Write-Host '  WARNING: VITE_CESIUM_ION_TOKEN not set in frontend\.env — globe imagery will be limited.' -ForegroundColor Yellow
}
$apiKey = Get-EnvValue 'frontend\.env' 'VITE_WORLDBASE_API_KEY'
$agentBus = Get-EnvValue 'frontend\.env' 'VITE_WORLDBASE_AGENT_BUS'

# 4) Write the compose env file (root .env, git-ignored)
$composeEnv = @"
# Auto-generated by scripts/start-docker.ps1 — do not commit.
VITE_CESIUM_ION_TOKEN=$cesium
VITE_WORLDBASE_API_KEY=$apiKey
VITE_WORLDBASE_AGENT_BUS=$agentBus
WORLDBASE_LAN=$lan
WORLDBASE_CORS_ORIGINS=https://$lan
WORLDBASE_REQUIRE_NODE_TOKEN=1
OLLAMA_HOST=host.docker.internal:11434
"@
Set-Content -Path (Join-Path $Root '.env') -Value $composeEnv -Encoding UTF8

# 5) Build + start
Write-Host ''
Write-Host 'docker compose up -d --build ...' -ForegroundColor Cyan
# docker writes progress to stderr; don't let that abort the script under -Stop
$prev = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
docker compose up -d --build 2>&1 | ForEach-Object { Write-Host $_ }
$code = $LASTEXITCODE
$ErrorActionPreference = $prev
if ($code -ne 0) { Write-Host "docker compose exited with code $code" -ForegroundColor Red; exit $code }

Write-Host ''
Write-Host 'intelshed is up:' -ForegroundColor Green
Write-Host "  Browser (this PC):  https://localhost   (accept the internal-CA warning once)"
Write-Host "  Browser (LAN):      https://$lan"
Write-Host "  Pi sync target:     https://$lan/api/node/ingest"
Write-Host "      -> on the Pi set: WORLDBASE_PC=$lan  WORLDBASE_SCHEME=https  WORLDBASE_VERIFY_TLS=0"
Write-Host ''
Write-Host 'Stop with: .\scripts\stop-docker.ps1' -ForegroundColor DarkGray
